build:
    environment:
        php:
            version: 5.5.9 # Common versions: 5.4, 5.5, 5.6, 7.0 or hhvm
    tests:
        override:
            -
                command: 'phpunit --bootstrap vendor/autoload.php --coverage-clover coverage.xml tests'
                coverage:
                    file: 'coverage.xml'
                    format: 'php-clover'
